// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Minesweeper.Game.Data;

#nullable disable

namespace Minesweeper.Game.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Minesweeper.Game.Models.GameScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatePlayed")
                        .HasColumnType("datetime2");

                    b.Property<int>("MinesCount")
                        .HasColumnType("int");

                    b.Property<int>("TimeInSeconds")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("GameScores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DatePlayed = new DateTime(2026, 4, 25, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            MinesCount = 20,
                            TimeInSeconds = 45,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            DatePlayed = new DateTime(2026, 4, 20, 14, 15, 0, 0, DateTimeKind.Unspecified),
                            MinesCount = 15,
                            TimeInSeconds = 30,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            DatePlayed = new DateTime(2026, 3, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            MinesCount = 40,
                            TimeInSeconds = 120,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Minesweeper.Game.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 4, 29, 0, 56, 49, 370, DateTimeKind.Local).AddTicks(1856),
                            PasswordHash = "$2a$11$qR7E.fBIdJ9V1N3F6mZ.OeZ/v.X0NqFzY7S3p4Q9U8h.vG1M2V4m6",
                            Username = "ProPlayer"
                        });
                });

            modelBuilder.Entity("Minesweeper.Game.Models.GameScore", b =>
                {
                    b.HasOne("Minesweeper.Game.Models.User", "User")
                        .WithMany("GameScores")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Minesweeper.Game.Models.User", b =>
                {
                    b.Navigation("GameScores");
                });
#pragma warning restore 612, 618
        }
    }
}
